### ISSUE TITLE
Errors due to delayed free pdf

### ISSUE THREAD

**Issue by tripplehelix** [artivis/rpipress-downloader#6]
The script currently throws errors as the magazine was released, but it's behind a timer. 

Would it be possible to grab the date of release of the current issue then calculate the time till release and display that instead of the error? I think they are released for free 2-3 weeks after print release.

**Comment by tripplehelix** [comment]
The only issue I see from this is the gap between PDF release and new release is the only time it'll download the PDF. If the new release has come out, it just errors and doesn't just instead download or make sure the previous magazine has been downloaded.

**Comment by tripplehelix** [comment]
For example, I ran the script today with an empty ~/rpipress folder, and it only downloaded one of the magazines and cast an error on the others. The error it throws 'you may need to wait' was a stop gap, between what it currently does and a fix.

**Comment by artivis** [comment]
I get your point. I can suggest 2 workarounds:
- write a service to run this daily, eventually you should download the latest issue
- always use the `--all` flag

Do you happen to know if a 'new issue' happens before a 'free issue'? In which case the first workaround wouldn't even work.

**Comment by tripplehelix** [comment]
If error, then download issue -1 ?

If issue -1 exists then "you are up to date"

"Do you happen to know if a 'new issue' happens before a 'free issue'? In which case the first workaround wouldn't even work."
I don't know their release schedule, I think it's like two or three weeks after paper release.
